import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import {
    performanceAPI,
    careerRecommendationAPI,
    studentProfileAPI,
    mappingAPI
} from '../../services/api';

import StudentProfileForm from './StudentProfileForm';
import SkillManagement from './SkillManagement';
import AcademicDataForm from './AcademicDataForm';

import './StudentDashboard.css';

const StudentDashboard = () => {
    const { user, loading: authLoading } = useAuth();

    const [performanceSummary, setPerformanceSummary] = useState(null);
    const [recommendations, setRecommendations] = useState([]);
    const [studentProfile, setStudentProfile] = useState(null);
    const [loading, setLoading] = useState(true);
    const [activeTab, setActiveTab] = useState('overview');
    const [hasProfile, setHasProfile] = useState(false);
    const [academicRecords, setAcademicRecords] = useState([]);
    const [skills, setSkills] = useState([]);
    const [showAcademicForm, setShowAcademicForm] = useState(false);
    const [autoGeneratedRecs, setAutoGeneratedRecs] = useState(false);
    const [assignedCounselor, setAssignedCounselor] = useState(null);

    useEffect(() => {
        if (!authLoading && user) {
            checkStudentProfile();
        }
    }, [user, authLoading]);

    useEffect(() => {
        setShowAcademicForm(false);
    }, [activeTab]);

    const checkStudentProfile = async () => {
        try {
            setLoading(true);
            if (!user?.id) return setHasProfile(false);

            const profileResponse = await studentProfileAPI.getProfileByUserId(user.id);

            if (profileResponse.data) {
                setStudentProfile(profileResponse.data);
                setHasProfile(true);
                await fetchStudentData(profileResponse.data.id);
                await autoGenerateRecommendations();
            } else {
                setHasProfile(false);
            }
        } catch {
            setHasProfile(false);
        } finally {
            setLoading(false);
        }
    };

    const fetchStudentData = async (studentId) => {
        try {
            const academicResponse = await performanceAPI.getAcademicPerformance(studentId);
            setAcademicRecords(academicResponse.data || []);

            const skillsResponse = await performanceAPI.getSkillAssessments(studentId);
            setSkills(skillsResponse.data || []);

            const performanceResponse = await performanceAPI.getPerformanceSummary(studentId);
            setPerformanceSummary(performanceResponse.data || null);

            const recsResponse = await careerRecommendationAPI.getMyRecommendations();
            setRecommendations(recsResponse.data || []);

            // ✅ Fetch Assigned Counselor
            try {
                const c = await mappingAPI.getMyCounselor();
                setAssignedCounselor(c.data || null);
            } catch {
                setAssignedCounselor(null);
            }

        } catch {}
    };

    const autoGenerateRecommendations = async () => {
        if (skills.length > 0 && recommendations.length === 0 && !autoGeneratedRecs) {
            const response = await careerRecommendationAPI.generateRecommendations();
            if (Array.isArray(response.data)) setRecommendations(response.data);
            setAutoGeneratedRecs(true);
        }
    };

    const generateRecommendations = async () => {
        if (skills.length === 0) {
            alert('❌ Please add skills first.');
            setActiveTab('skills');
            return;
        }

        await careerRecommendationAPI.generateRecommendations();
        const recsResponse = await careerRecommendationAPI.getMyRecommendations();
        setRecommendations(recsResponse.data || []);
        alert('✅ Recommendations updated!');
    };

    const refreshData = async () => {
        if (studentProfile) await fetchStudentData(studentProfile.id);
    };

    if (loading) return <div className="loading"><p>Loading your dashboard...</p></div>;
    if (!hasProfile) return <StudentProfileForm onProfileCreated={checkStudentProfile} />;

    return (
        <div className="student-dashboard">

            {/* HEADER */}
            <div className="welcome-card">
                <div className="welcome-left">
                    <h1>Student Dashboard</h1>
                    <p>Welcome back, <strong>{studentProfile.fullName}</strong>! 👋</p>
                    <small>🎓 {studentProfile.universityName}</small>
                </div>
                <button onClick={refreshData} className="btn-refresh">🔄 Refresh Data</button>
            </div>

            {/* TABS */}
            <div className="dashboard-tabs">
                <button className={activeTab === 'overview' ? 'tab-active' : ''} onClick={() => setActiveTab('overview')}>📊 Overview</button>
                <button className={activeTab === 'performance' ? 'tab-active' : ''} onClick={() => setActiveTab('performance')}>📈 Performance</button>
                <button className={activeTab === 'skills' ? 'tab-active' : ''} onClick={() => setActiveTab('skills')}>🎯 My Skills</button>
                <button className={activeTab === 'careers' ? 'tab-active' : ''} onClick={() => setActiveTab('careers')}>💼 Career Recommendations</button>
            </div>

            <div className="tab-content">

                {/* OVERVIEW */}
                {activeTab === 'overview' && (
                    <div className="section-card">
                        <h3>Quick Actions</h3>

                        <div className="action-buttons">
                            <button className="btn-primary" onClick={() => setActiveTab('skills')}>🎯 Add / Manage Skills</button>

                            <button
                                className="btn-primary"
                                onClick={() => {
                                    setActiveTab('performance');
                                    setTimeout(() => setShowAcademicForm(true), 50);
                                }}>
                                📚 Add Academic Data
                            </button>

                            <button className="btn-primary" onClick={generateRecommendations}>💼 Generate Career Matches</button>
                        </div>

                        {/* ✅ Assigned Counselor Card */}
                        {/* ✅ Assigned Counselor Card */}
                        <div className="counselor-card">
                            <h3>👩‍🏫 Assigned Counselor</h3>

                            {assignedCounselor ? (
                                <>
                                    <p><strong>{assignedCounselor.fullName}</strong></p>
                                    <p>{assignedCounselor.department}</p>
                                    <p>Experience: {assignedCounselor.experienceYears} years</p>
                                    <p>📞 {assignedCounselor.contactNumber}</p>

                                    {assignedCounselor.feedback ? (
                                        <div className="feedback-box">
                                            <h4>📝 Latest Counselor Feedback</h4>
                                            <p>"{assignedCounselor.feedback}"</p>
                                            {assignedCounselor.lastUpdated && (
                                                <small>Last updated: {new Date(assignedCounselor.lastUpdated).toLocaleDateString()}</small>
                                            )}
                                        </div>
                                    ) : (
                                        <p style={{ opacity: 0.7 }}>No feedback given yet.</p>
                                    )}
                                </>
                            ) : (
                                <p>No counselor has been assigned yet.</p>
                            )}
                        </div>


                    </div>
                )}

                {/* PERFORMANCE */}
                {activeTab === 'performance' && (
                    <div className="section-card">

                        <div className="performance-header">
                            <h3>📈 Academic Performance</h3>
                            <button className="btn-primary" onClick={() => setShowAcademicForm(true)}>➕ Add Academic Data</button>
                        </div>

                        {showAcademicForm && (
                            <AcademicDataForm
                                studentId={studentProfile.id}
                                onDataAdded={() => { setShowAcademicForm(false); refreshData(); }}
                                onCancel={() => setShowAcademicForm(false)}
                            />
                        )}

                        {performanceSummary && (
                            <div className="performance-summary-card">
                                <h4>📊 Performance Summary</h4>
                                <p><strong>Average Grade:</strong> {performanceSummary.averageGrade?.toFixed(2) || 'N/A'}</p>
                                <p><strong>Top Skills:</strong> {performanceSummary.topSkills || 'No skills yet'}</p>
                            </div>
                        )}

                        <div className="skills-summary-card">
                            <h4>🎯 Skills Summary</h4>
                            <p><strong>{skills.length}</strong> Total Skills</p>
                            <p><strong>{skills.filter(s => s.score >= 76).length}</strong> Advanced Skills</p>
                            {skills.length > 0 && (
                                <p><strong>{Math.round(skills.reduce((a, b) => a + b.score, 0) / skills.length)}%</strong> Average Proficiency</p>
                            )}
                        </div>
                    </div>
                )}

                {/* SKILLS */}
                {activeTab === 'skills' && <SkillManagement onSkillsUpdated={refreshData} />}

                {/* CAREERS */}
                {activeTab === 'careers' && (
                    <div className="section-card">
                        <h3>💼 Career Recommendations</h3>
                        <button className="btn-primary" onClick={generateRecommendations}>🔄 Refresh Recommendations</button>

                        {recommendations.length === 0 ? (
                            <p>No recommendations yet. Generate to view results.</p>
                        ) : (
                            <div className="recommendations-list">
                                {recommendations.map((rec) => (
                                    <div key={rec.id} className="rec-card">
                                        <div className="rec-header">
                                            <h4>{rec.careerPath?.careerName}</h4>
                                            <span className={`match-chip ${rec.matchLevel?.toLowerCase()}`}>
                                                {rec.matchLevel} Match
                                            </span>
                                        </div>
                                        <p className="rec-desc">{rec.careerPath?.description}</p>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
};

export default StudentDashboard;
